CREATE DATABASE CamelsRUs;
GO

USE CamelsRUs;

CREATE TABLE dbo.Camels (
	Id INT IDENTITY (1, 1) PRIMARY KEY,
	Name VARCHAR (255) NOT NULL,
	Species VARCHAR (255) NOT NULL,
	Age INT NOT NULL
);

CREATE TABLE dbo.Ranches (
	Id INT IDENTITY (1, 1) PRIMARY KEY,
	Name VARCHAR (255) NOT NULL
);

CREATE TABLE dbo.Placements (
	Id INT IDENTITY (1, 1) PRIMARY KEY,
	CamelId INT NOT NULL,
	RanchId INT,
	FOREIGN KEY (CamelId) REFERENCES Camels (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (RanchId) REFERENCES Ranches (Id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

